### ISSUE TITLE
Payment App Registration: Same Origin is problematic for identifying_url

### ISSUE THREAD

**Issue by LaurentCastillo** [WICG/historical-paymentrequest#66]
identifying_url is used to match the payment method url in the payment request, which is typically the payment scheme in a traditional card system (i.e. Visa, Mastercard, Amex, etc...). So limiting payment app to the same origin as the identifying_url means we're limiting payment app to scheme-based app (so no issuing bank payment app for instance). It feels very unatural for issuing banks that actually own the account and the card number to not be able to use the card in their own payment app.

It should be possible to define a payment method that can be used by multiple payment apps, but it's not possible with the current constraint.

**Comment by webpayments** [comment]
+1 I also have big concerns about origin bounded Payment App.

we need to some mechanisms
for example
get user consent to use Payment App at different origins.
or
validate certificate of Payment App (if PKI is used). allow multi-origin
when the certificate is valid.


On Tue, Feb 23, 2016 at 2:51 PM, Laurent Castillo <notifications@github.com>
wrote:

> identifying_url is used to match the payment method url in the payment
> request, which is typically the payment scheme in a traditional card system
> (i.e. Visa, Mastercard, Amex, etc...). So limiting payment app to the same
> origin as the identifying_url means we're limiting payment app to
> scheme-based app (so no issuing bank payment app for instance). It feels
> very unatural for issuing banks that actually own the account and the card
> number to not be able to use the card in their own payment app.
>
> It should be possible to define a payment method that can be used by
> multiple payment apps, but it's not possible with the current constraint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/66>.
>



-- 
Mountie Lee

PayGate
CTO, CISSP
Tel : +82 2 2140 2700
E-Mail : mountie@paygate.net

**Comment by adrianhopebailie** [comment]
:+1: I think it's a hard requirement that payee's don't need to list explicit support for payment apps.

**Comment by dlongley** [comment]
:+1:

**Comment by zkoch** [comment]
So I think the real problem we're driving at is this: registered payment apps should be able to support payment methods independent of their own `identifying_url`. For example, BobPay should be able to support BobPay payments as well as the ability to return back a normal PAN.

In principle, I agree. Here's the problem I'm looking for help solving with registration:

A payment app registering with the ability to **support** a particular payment method does **not** mean the user using that payment app has that particular payment method available. As an example: A merchant supports Visa and MC only. A user then registers AliceWallet, which support Visa and MC, but the user only has an AMEX card inside of AliceWallet.

In my opinion, AliceWallet should not be presented as a payment option because the user doesn't currently have any payment methods inside of AliceWallet that intersect with the set of supported instruments from the merchant, i.e. Visa and MC.

Open to suggestions on how to solve this problem.

**Comment by webpayments** [comment]
Shouldn't AliceWallet be exposing which payment method(s) are registered?
Is there some privacy concern if this is exposed to the user agent?  I
don't think so.  As a user you are consenting to connecting your wallet to
the user agent, so that the user agent acts as an arbitrator between
merchant sites and the wallet.  Part of that arbitration is only exposing
wallets as options that can satisfy the request.

On Wed, Feb 24, 2016 at 9:37 AM, Zach Koch <notifications@github.com> wrote:

> So I think the real problem we're driving at is this: registered payment
> apps should be able to support payment methods independent of their own
> identifying_url. For example, BobPay should be able to support BobPay
> payments as well as the ability to return back a normal PAN.
>
> In principle, I agree. Here's the problem I'm looking for help solving
> with registration:
>
> A payment app registering with the ability to *support* a particular
> payment method does *not* mean the user using that payment app has that
> particular payment method available. As an example: A merchant supports
> Visa and MC only. A user then registers AliceWallet, which support Visa and
> MC, but the user only has an AMEX card inside of AliceWallet.
>
> In my opinion, AliceWallet should not be presented as a payment option
> because the user doesn't currently have any payment methods inside of
> AliceWallet that intersect with the set of supported instruments from the
> merchant, i.e. Visa and MC.
>
> Open to suggestions on how to solve this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/66#issuecomment-188371056>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by dlongley** [comment]
@zkoch,

> Open to suggestions on how to solve this problem.

Perhaps it would help to look at this as a bootstrapping problem.

Suppose:

1. When a Payment App registers itself, it indicates which payment methods it supports.
1. When a user adds a payment instrument/credential to a Payment App instance to enable the use of a payment method, that instance can notify the browser that a payment method is now available (in addition to just being supported).

Now:

1. A user installs a Payment App. At this point, the user hasn't done anything with the app so it can't know if the user has an instrument/credential for a particular method.
1. If a user navigates to a merchant site and tries to pay for something, the browser, at this point, will need to show a UI that indicates that they don't have a payment instrument/credential registered with any of their Payment Apps yet, but they do have a Payment App they can choose and go and register one with (and then pay).
1. The user picks the Payment App that they can register an instrument/credential with and uses it to register and pay. The Payment App notifies the browser that they were able to pay with a particular method (this could just be the browser looking at the payment response and seeing it happened ... or it could be an explicit call/message).
1. Next time the user tries to buy something using the same payment method, the browser UI will be able to show them that they can pay with a particular Payment App right away.

Is this an acceptable user experience?

**Comment by webpayments** [comment]
I think it is a fine user experience.  However, we MUST be able to handle
the case where the user has a payment app (service) they have been using
for years, and then the user installs an instance of that payment app on a
new device.  It would be cleaner to have the user agent interrogate the
payment app to determine the list of supported payment methods.  Or, and I
think this is better, have the user agent pass through to the payment app
the list of methods the merchant supports, and the payment app responds
with the subset that is available.

On Wed, Feb 24, 2016 at 10:09 AM, Dave Longley <notifications@github.com>
wrote:

> @zkoch <https://github.com/zkoch>,
>
> Open to suggestions on how to solve this problem.
>
> Perhaps it would help to look at this as a bootstrapping problem.
>
> Suppose:
>
>    1. When a Payment App registers itself, it indicates which payment
>    methods it supports.
>    2. When a user adds a payment instrument/credential to a Payment App
>    instance to enable the use of a payment method, that instance can notify
>    the browser that a payment method is now available (in addition to just
>    being supported).
>
> Now:
>
>    1. A user installs a Payment App. At this point, the user hasn't done
>    anything with the app so it can't know if the user has an
>    instrument/credential for a particular method.
>    2. If a user navigates to a merchant site and tries to pay for
>    something, the browser, at this point, will need to show a UI that
>    indicates that they don't have a payment instrument/credential registered
>    with any of their Payment Apps yet, but they do have a Payment App they can
>    choose and go and register one with (and then pay).
>    3. The user picks the Payment App that they can register an
>    instrument/credential with and uses it to register and pay. The Payment App
>    notifies the browser that they were able to pay with a particular method
>    (this could just be the browser looking at the payment response and seeing
>    it happened ... or it could be an explicit call/message).
>    4. Next time the user tries to buy something using the same payment
>    method, the browser UI will be able to show them that they can pay with a
>    particular Payment App right away.
>
> Is this an acceptable user experience?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/66#issuecomment-188386629>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by dlongley** [comment]
> It would be cleaner to have the user agent interrogate the
payment app to determine the list of supported payment methods.  Or, and I
think this is better, have the user agent pass through to the payment app
the list of methods the merchant supports, and the payment app responds
with the subset that is available.

I think that could work -- except there might be an authentication problem with this approach. The user needs to authenticate with the Payment App in order for it to be able to be respond (on behalf of the user) to the browser with what methods are available. This potentially brings up more questions than it answers -- like how the browser will get user consent and security credentials to authenticate with a variety of different Payment Apps? Right now, how authentication happens with a particular Payment App is of no consequence to the browser -- this may require breaking that abstraction.

**Comment by burdges** [comment]
I'm not completely sure I understand the issue here.

We encountered important same origin policy issues when building the [Taler](https://api.taler.net/#web-integration-handbook) [wallet](http://www.git.taler.net/?p=wallet.git;a=tree), both first when building our first wallet, and then again when updating it from XUL to WebExtensions.  In places, we felt the need to ensure that particular paths were a hard stop for the current page and forced a page transition, sometimes even for some error paths.  In all cases, switching from the less restrictive XUL same origin policy to the more restrictive WebExtensions same origin policy improved our payment application's security.

A priori, I'd expect the browser's origin policy requirements should be treated as absolute.  All payments will need to depart the merchants page to access anything that the user can trust and that can access the user's identity, payment methods, claims, etc.  It doesn't necessary need to replace the current page, but it must not allow repeated back and forth with the merchant page.

We also found a significant difference with the origin policy issues between payments that require the user interaction, and our hypothetical future "valueless" auto-pay currencies, but that's not an issue here.

**Comment by LaurentCastillo** [comment]
> Open to suggestions on how to solve this problem.

An alternative to Dave's proposal is to also register the payment instruments inside a payment app (or at least an id that the payment app can recognize). That way, the user agent knowsif an app has valid instruments associated with a payment method.

It has the added benefit of removing one click during the payment flow: from 'select payment app->trigger app->select instrument', we go to 'select instrument and associated app->trigger app with selected instrument id'

**Comment by webpayments** [comment]
+1 from my side – this is what I called ‘parameterization’ of the payment app. And it is as most real-world instruments seem to work (e.g. SmartCard Applets using ‘profiles’ for a concrete instantiation of a ‘card’)

Jörg

**Comment by dlongley** [comment]
@LaurentCastillo,

> An alternative to Dave's proposal is to also register the payment instruments inside a payment app (or at least an id that the payment app can recognize).

How would this registration work? How, specifically, is it different from what I proposed?

In my proposal, my intent was to communicate that the payment instruments would be registered inside the payment app. I left open how the browser becomes aware of this information, however -- with a suggestion that it could be as simple as tracking payment responses, but we could also have an API call or send message or something. Shane recommended a query or declarative mechanism but that may have authentication issues.

How do you recommend the browser become aware?

Perhaps we mean different things when we say "registered inside the payment app"?

**Comment by webpayments** [comment]
I withdraw my query mechanism idea.  I was only thinking of local apps /
extensions.  There are cross origin problems and authentication problems
with my model when the payment app is registered with a user agent, but it
manifests as an iframe / popup or whatever.  Querying a remote server that
retains the information would be an authentication nightmare.  What I would
suggest is that the registration mechanism includes a way of informing the
user agent of the payment instruments the user has, and that it
synchronizes that list each time it is invoked.

On Wed, Feb 24, 2016 at 12:19 PM, Dave Longley <notifications@github.com>
wrote:

> @LaurentCastillo <https://github.com/LaurentCastillo>,
>
> An alternative to Dave's proposal is to also register the payment
> instruments inside a payment app (or at least an id that the payment app
> can recognize).
>
> How would this registration work? How, specifically, is it different from
> what I proposed?
>
> In my proposal, my intent was to communicate that the payment instruments
> would be registered inside the payment app. I left open how the browser
> becomes aware of this information, however -- with a suggestion that it
> could be as simple as tracking payment responses, but we could also have an
> API call or send message or something. Shane recommended a query or
> declarative mechanism but that may have authentication issues.
>
> How do you recommend the browser become aware?
>
> Perhaps we mean different things when we say "registered inside the
> payment app"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/66#issuecomment-188438915>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by LaurentCastillo** [comment]
@dlongley 

> How would this registration work? How, specifically, is it different from what I proposed?

I maybe wrongly reading between the lines, but 'The user picks the Payment App' suggests a model in which the user picks a payment app registered in the browser, then picks a payment instrument registered in the payment app. I suggest skipping a step by registering (a link to) payment instruments directly in the browser, so that users can pick an instrument directly and implicitely select the corresponding payment app.

> How do you recommend the browser become aware?

Good question, maybe an additional explicit call registerPaymentInstrument ?

**Comment by dlongley** [comment]
@LaurentCastillo,

> I suggest skipping a step by registering (a link to) payment instruments directly in the browser, so that users can pick an instrument directly and implicitely select the corresponding payment app.

Ok, that makes sense and is along the lines of what I was going for w/the Payment App making a call or sending a message to indicate a payment instrument/credential had been registered.

> Good question, maybe an additional explicit call registerPaymentInstrument ?

Yeah, something to consider. I'm not sure yet, but there may be some overlap with VCTF here -- or at least there's some potential for reusing ideas for "cloud-based" payment credentials or payment credentials that people can carry with them (through a web service or through a hardware device/similar) so they can register them easily on new devices.

**Comment by mattsaxon** [comment]
@LaurentCastillo 

>I maybe wrongly reading between the lines, but 'The user picks the Payment App' suggests a model in which the user picks a payment app registered in the browser, then picks a payment instrument registered in the payment app. I suggest skipping a step by registering (a link to) payment instruments directly in the browser, so that users can pick an instrument directly and implicitely select the corresponding payment app.

Whilst that may work in simple cases and provide a better user experience in those, how might this work when multiple payment application have the same payment instrument registered? For example a single card may be registered with MasterPass and Google Payments. This could get quite confusing, particularly if a Website support payments from both of those and say Visa, there could be 3 different apps that could present the Visa card information.

@adrianba 

In the demo http://github.adrianba.net/paymentrequest-demo/ when the users selects a card, are they selecting a payment instrument or a payment application?

**Comment by webpayments** [comment]
Well said. Our user concept tests clearly indicate that users won’t support multiple such apps.

Cheers,
                Jörg

**Comment by halindrome** [comment]
Jorg,

Can you confirm that what you are saying is that in environment you have tested, users are not interested in / refuse to install or use more than one payment app in a given environment?  And is there any research data you can share on this?

**Comment by webpayments** [comment]
Hello Shane,

Something like that, I recall, was expressed by David Ezell as an outcome of a NACS-study in Sapporo. (I still hear ‘Certainly not another app!’ ringing in my ears…)

What I can confirm from our studies are confirmative statements for having every payment, identity and entitlement instrument in on place. Citing results of a Customer Advisory Board format held in June 2015 at T-Labs:
“Of all the claimed positive aspects, the central place for all identity data was ranked as the most valuable.“

A finding from an online survey conducted in Oct 2015 with about 235 counted participants says:
“The combination of services is the main benefit”

Both refer to the solution we have demoed at several occasions, which puts together identity, payment and other credentials (from the POV of a user, not the techie-interpretation of the term ☺). They, thus, give feedback on the quality perceived with such solution, which was not contrasted with any approach of a less harmonized nature. Rather it was compared to current reality (dozens of passwords, PINs, many different cards, coupons, etc.)

Regards,
                Jörg

**Comment by halindrome** [comment]
That's really good data.  Thanks!

I personally agree with this.  So it would be good if the architecture permitted it to *seem* as if there is a single solution in place.  If the reality is that I installed the XYZ loyalty card app and that is one of my available payment methods, as long as the experience is more or less smooth, I expect we will be fine.  I also expect the situation will be self correcting. Payment apps that do not integrate well / have a less comfortable and familiar user experience will either 1) not be approved by the relevant app store, or 2) get quickly panned by their users for not working well.

**Comment by msporny** [comment]
This is the wrong home for this issue, it should be migrated here:

https://github.com/w3c/browser-payment-api/issues

@LaurentCastillo would you mind moving the issue there?
